# Generated by Django 3.1.5 on 2021-04-16 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
