# Generated by Django 3.1.5 on 2021-04-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0002_auto_20210416_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_file',
        ),
        migrations.AddField(
            model_name='project',
            name='index_path',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='upload_file',
            field=models.FileField(upload_to='projects/zipfiles'),
        ),
    ]
