# Generated by Django 3.1.7 on 2021-04-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0003_auto_20210418_0314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
