# Generated by Django 3.1.5 on 2021-02-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UploadProjects',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
    ]
