# Generated by Django 3.1.7 on 2021-03-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='path',
        ),
        migrations.AddField(
            model_name='projects',
            name='html_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='pic_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
