# Generated by Django 3.1.5 on 2021-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0002_auto_20210314_1919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadProjects',
        ),
        migrations.AddField(
            model_name='projects',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
