# Generated by Django 3.1.7 on 2021-03-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0004_projects_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='comment',
        ),
        migrations.AddField(
            model_name='projects',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
